name: Comment

on:
  issue_comment:
    types:
      - created

jobs:
  release_next:
    name: release:next
    runs-on: ubuntu-latest

    if: |
      github.event.issue.pull_request &&
      (github.event.sender.login == 'alessbell' || github.event.sender.login == 'jerelmiller') &&
      startsWith(github.event.comment.body, '/release:pr')

    steps:
      - uses: alessbell/pull-request-comment-branch@v2.1.0
        id: comment-branch

      - name: Get sha
        id: parse-sha
        run: |
          if [ "${{ steps.comment-branch.outputs.head_owner }}" == "alessbell" ]; then
            headSha="${{ steps.comment-branch.outputs.head_sha }}"
            echo $headSha
            echo "sha=${{ steps.comment-branch.outputs.head_sha }}" >> "${GITHUB_OUTPUT}"
          else
            shaFromComment="$(echo '${{ github.event.comment.body }}' | tr -s ' ' | cut -d ' ' -f2)"
            echo $shaFromComment
            echo "sha=$shaFromComment" >> "${GITHUB_OUTPUT}"
          fi

      - name: Echo comment branch values
        run: |
          echo "${{steps.comment-branch.outputs.head_owner}} ${{steps.comment-branch.outputs.head_repo}} ${{ steps.comment-branch.outputs.head_ref }}"

      - name: Checkout head ref
        uses: actions/checkout@v3
        with:
          ## specify the owner + repository in order to checkout the fork
          ## for community PRs
          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
          ref: ${{ steps.parse-sha.outputs.sha }}
          fetch-depth: 0

      - name: Detect new changesets
        id: added-files
        run: |
          echo "changesets=$(git diff --name-only --diff-filter=A ${{ steps.comment-branch.outputs.base_sha }} ${{ steps.parse-sha.outputs.sha }} .changeset/*.md)" >> "$GITHUB_OUTPUT"

      - name: Echo added files
        run: echo "${{ steps.added-files.outputs.changesets }}"

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: '.changeset/pre.json'

      - name: Exit pre mode if pre.json exists
        id: exit-pre-mode
        # Changesets prevents us from generating a snapshot release
        # if we're in prerelease mode, so we remove `pre.json` if it exists
        # (but do not commit this change since we want the branch to remain
        # in pre mode)
        if: steps.check_files.outputs.files_exists == 'true'
        run: rm .changeset/pre.json

      - name: Add comment if no changeset exists
        if: ${{ steps.added-files.outputs.changesets == '' }}
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please add a changeset via `npx changeset` before attempting a snapshot release.

      # https://github.com/atlassian/changesets/blob/master/docs/snapshot-releases.md
      - name: Release to pr tag
        if: ${{ steps.added-files.outputs.changesets != '' }}
        run: |
          npx changeset version --snapshot pr-${{ github.event.issue.number }} && npm i
          npm run build && npx changeset publish --no-git-tag --snapshot --tag pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get released version
        if: ${{ steps.added-files.outputs.changesets != '' }}
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Create comment
        if: ${{ steps.added-files.outputs.changesets != '' }}
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            A new release has been made for this pull request. You can install it with `npm i good-snow-tire-demo@${{ steps.version.outputs.version }}`.
